# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"

lane :build do

  build_app(
   project: "TodoList.xcodeproj",
    configuration: "Debug",
    scheme: "TodoList",
    silent: true,
    clean: false,
    export_method: "development",
    output_directory: "Build", # Destination directory. Defaults to current directory.
    output_name: "my-app.ipa",       # specify the name of the .ipa file to generate (including file extension)
    #sdk: "iOS 11.1"        # use SDK as the name or path of the base SDK when building the project.
  )

 # appcenter_upload(
 #  api_token: "b984214da7624272c75a7e5832509ce2550115a3",
 #   owner_name: "yanoratheesh-gmail.com",
 #   owner_type: "user", # Default is user - set to organization for appcenter organizations
 #   app_name: "TodoList",
    #file: "/Users/ratheesh/Desktop/Ratheesh/SwiftUI/TodoList/path/to/dir",
 #   notify_testers: true # Set to false if you don't want to notify testers of your new release (default: `false`)
 # )
end

end


